# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kmc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kmc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tkmc.proto\x12\x06kmc.v1\"<\n\x13\x41pplyWorkKeyRequest\x12\x11\n\talgorithm\x18\x01 \x01(\t\x12\x12\n\nkey_length\x18\x02 \x01(\r\"=\n\x14RotateWorkKeyRequest\x12\x11\n\talgorithm\x18\x01 \x01(\t\x12\x12\n\nkey_length\x18\x02 \x01(\r\"\xc3\x01\n\x0fWorkKeyResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06key_id\x18\x02 \x01(\t\x12\x11\n\talgorithm\x18\x03 \x01(\t\x12\x12\n\nkey_length\x18\x04 \x01(\r\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x12\n\ncreated_at\x18\x06 \x01(\t\x12\x12\n\nexpires_at\x18\x07 \x01(\t\x12\x17\n\x0f\x65xpires_at_unix\x18\x08 \x01(\x03\x12\x14\n\x0ckey_material\x18\t \x01(\x0c\".\n\rErrorResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"r\n\nSdkRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12$\n\x07\x65ncrypt\x18\x02 \x01(\x0b\x32\x11.kmc.v1.EncryptOpH\x00\x12$\n\x07\x64\x65\x63rypt\x18\x03 \x01(\x0b\x32\x11.kmc.v1.DecryptOpH\x00\x42\x04\n\x02op\"\x1e\n\tEncryptOp\x12\x11\n\tplaintext\x18\x01 \x01(\x0c\"P\n\tDecryptOp\x12\x0e\n\x06key_id\x18\x01 \x01(\t\x12\r\n\x05nonce\x18\x02 \x01(\x0c\x12\x12\n\nciphertext\x18\x03 \x01(\x0c\x12\x10\n\x08\x61uth_tag\x18\x04 \x01(\x0c\"\x98\x01\n\x0bSdkResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x0e\n\x06key_id\x18\x04 \x01(\t\x12\r\n\x05nonce\x18\x05 \x01(\x0c\x12\x12\n\nciphertext\x18\x06 \x01(\x0c\x12\x10\n\x08\x61uth_tag\x18\x07 \x01(\x0c\x12\x11\n\tplaintext\x18\x08 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kmc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPLYWORKKEYREQUEST']._serialized_start=21
  _globals['_APPLYWORKKEYREQUEST']._serialized_end=81
  _globals['_ROTATEWORKKEYREQUEST']._serialized_start=83
  _globals['_ROTATEWORKKEYREQUEST']._serialized_end=144
  _globals['_WORKKEYRESPONSE']._serialized_start=147
  _globals['_WORKKEYRESPONSE']._serialized_end=342
  _globals['_ERRORRESPONSE']._serialized_start=344
  _globals['_ERRORRESPONSE']._serialized_end=390
  _globals['_SDKREQUEST']._serialized_start=392
  _globals['_SDKREQUEST']._serialized_end=506
  _globals['_ENCRYPTOP']._serialized_start=508
  _globals['_ENCRYPTOP']._serialized_end=538
  _globals['_DECRYPTOP']._serialized_start=540
  _globals['_DECRYPTOP']._serialized_end=620
  _globals['_SDKRESPONSE']._serialized_start=623
  _globals['_SDKRESPONSE']._serialized_end=775
# @@protoc_insertion_point(module_scope)
